export const fileToBase64 = (file: File): Promise<string> => {
  return new Promise((resolve, reject) => {
    const reader = new FileReader();
    reader.readAsDataURL(file);
    reader.onload = () => resolve(reader.result as string);
    reader.onerror = (error) => reject(error);
  });
};

export const base64ToBytes = (base64: string): Uint8Array => {
  const binaryString = atob(base64.split(',')[1]); // Remove data URI prefix
  const len = binaryString.length;
  const bytes = new Uint8Array(len);
  for (let i = 0; i < len; i++) {
    bytes[i] = binaryString.charCodeAt(i);
  }
  return bytes;
};

export const downloadImage = (imageUrl: string, filename: string = 'edited_image.png'): void => {
  const link = document.createElement('a');
  link.href = imageUrl;
  link.download = filename;
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
};

export const copyImageToClipboard = async (imageUrl: string): Promise<void> => {
  try {
    const response = await fetch(imageUrl);
    const blob = await response.blob();
    await navigator.clipboard.write([
      new ClipboardItem({
        [blob.type]: blob,
      }),
    ]);
    console.log('Image copied to clipboard!');
  } catch (err) {
    console.error('Failed to copy image:', err);
    alert('Failed to copy image. Your browser might not support this feature or permission was denied.');
  }
};

export const shareImage = async (imageUrl: string, filename: string = 'shared_image.png'): Promise<void> => {
  if (!navigator.share) {
    alert('Web Share API is not supported in your browser.');
    console.warn('Web Share API not supported.');
    return;
  }

  try {
    const response = await fetch(imageUrl);
    const blob = await response.blob();
    const file = new File([blob], filename, { type: blob.type });

    if (navigator.canShare && navigator.canShare({ files: [file] })) {
      await navigator.share({
        files: [file],
        title: 'Generated Image',
        text: 'Check out this image generated by Nano Banana Image Editor!',
      });
      console.log('Image shared successfully!');
    } else {
      // Fallback if sharing files is not supported (but share API is)
      await navigator.share({
        url: imageUrl,
        title: 'Generated Image',
        text: 'Check out this image generated by Nano Banana Image Editor!',
      });
      console.log('Image shared via URL fallback.');
    }
  } catch (error) {
    if (error instanceof DOMException && error.name === "AbortError") {
      console.log('Image sharing cancelled by user.');
    } else {
      console.error('Error sharing image:', error);
      alert('Failed to share image. Please try again.');
    }
  }
};